# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Qt\8-puzzle-ai\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameGUI(object):
    def setupUi(self, GameGUI):
        GameGUI.setObjectName("GameGUI")
        GameGUI.resize(800, 600)

        self.retranslateUi(GameGUI)
        QtCore.QMetaObject.connectSlotsByName(GameGUI)

    def retranslateUi(self, GameGUI):
        _translate = QtCore.QCoreApplication.translate
        GameGUI.setWindowTitle(_translate("GameGUI", "GameGUI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameGUI = QtWidgets.QWidget()
    ui = Ui_GameGUI()
    ui.setupUi(GameGUI)
    GameGUI.show()
    sys.exit(app.exec_())
