# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Qt\8-puzzle-ai\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameGUI(object):
    def setupUi(self, GameGUI):
        GameGUI.setObjectName("GameGUI")
        GameGUI.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameGUI.sizePolicy().hasHeightForWidth())
        GameGUI.setSizePolicy(sizePolicy)
        GameGUI.setMinimumSize(QtCore.QSize(640, 480))
        GameGUI.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GameGUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GameGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.game_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.game_grid.setContentsMargins(0, 0, 0, 0)
        self.game_grid.setObjectName("game_grid")
        self.grid_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_21.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_21.setObjectName("grid_21")
        self.game_grid.addWidget(self.grid_21, 2, 1, 1, 1)
        self.grid_02 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_02.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_02.setObjectName("grid_02")
        self.game_grid.addWidget(self.grid_02, 0, 2, 1, 1)
        self.grid_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_11.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_11.setObjectName("grid_11")
        self.game_grid.addWidget(self.grid_11, 1, 1, 1, 1)
        self.grid_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_20.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_20.setObjectName("grid_20")
        self.game_grid.addWidget(self.grid_20, 2, 0, 1, 1)
        self.grid_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_22.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_22.setObjectName("grid_22")
        self.game_grid.addWidget(self.grid_22, 2, 2, 1, 1)
        self.grid_01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_01.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_01.setObjectName("grid_01")
        self.game_grid.addWidget(self.grid_01, 0, 1, 1, 1)
        self.grid_00 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_00.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_00.setObjectName("grid_00")
        self.game_grid.addWidget(self.grid_00, 0, 0, 1, 1)
        self.grid_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_12.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_12.setObjectName("grid_12")
        self.game_grid.addWidget(self.grid_12, 1, 2, 1, 1)
        self.grid_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.grid_10.setMaximumSize(QtCore.QSize(130, 130))
        self.grid_10.setObjectName("grid_10")
        self.game_grid.addWidget(self.grid_10, 1, 0, 1, 1)
        self.solve_btn = QtWidgets.QPushButton(self.centralwidget)
        self.solve_btn.setGeometry(QtCore.QRect(470, 400, 141, 31))
        self.solve_btn.setObjectName("solve_btn")
        self.algorithm_box = QtWidgets.QGroupBox(self.centralwidget)
        self.algorithm_box.setGeometry(QtCore.QRect(470, 10, 141, 61))
        self.algorithm_box.setObjectName("algorithm_box")
        self.comboBox = QtWidgets.QComboBox(self.algorithm_box)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.configuration_box = QtWidgets.QGroupBox(self.centralwidget)
        self.configuration_box.setGeometry(QtCore.QRect(470, 90, 141, 161))
        self.configuration_box.setObjectName("configuration_box")
        self.custom_config = QtWidgets.QTextEdit(self.configuration_box)
        self.custom_config.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.custom_config.setObjectName("custom_config")
        self.set_btn = QtWidgets.QPushButton(self.configuration_box)
        self.set_btn.setGeometry(QtCore.QRect(60, 60, 71, 31))
        self.set_btn.setObjectName("set_btn")
        self.shuffle_btn = QtWidgets.QPushButton(self.configuration_box)
        self.shuffle_btn.setGeometry(QtCore.QRect(10, 120, 121, 31))
        self.shuffle_btn.setObjectName("shuffle_btn")
        self.line = QtWidgets.QFrame(self.configuration_box)
        self.line.setGeometry(QtCore.QRect(15, 100, 111, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.options_box = QtWidgets.QGroupBox(self.centralwidget)
        self.options_box.setGeometry(QtCore.QRect(470, 270, 141, 111))
        self.options_box.setObjectName("options_box")
        self.option_ch_1 = QtWidgets.QCheckBox(self.options_box)
        self.option_ch_1.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.option_ch_1.setObjectName("option_ch_1")
        self.option_ch_2 = QtWidgets.QCheckBox(self.options_box)
        self.option_ch_2.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.option_ch_2.setObjectName("option_ch_2")
        self.option_ch_3 = QtWidgets.QCheckBox(self.options_box)
        self.option_ch_3.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.option_ch_3.setObjectName("option_ch_3")
        GameGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GameGUI)
        self.statusbar.setObjectName("statusbar")
        GameGUI.setStatusBar(self.statusbar)

        self.retranslateUi(GameGUI)
        QtCore.QMetaObject.connectSlotsByName(GameGUI)

    def retranslateUi(self, GameGUI):
        _translate = QtCore.QCoreApplication.translate
        GameGUI.setWindowTitle(_translate("GameGUI", "8 Puzzle Game"))
        self.grid_21.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/8.png\"/></p></body></html>"))
        self.grid_02.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/3.png\"/></p></body></html>"))
        self.grid_11.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/5.png\"/></p></body></html>"))
        self.grid_20.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/7.png\"/></p></body></html>"))
        self.grid_22.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/default.png\"/></p></body></html>"))
        self.grid_01.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/2.png\"/></p><p><br/></p></body></html>"))
        self.grid_00.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/1.png\"/></p></body></html>"))
        self.grid_12.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/6.png\"/></p></body></html>"))
        self.grid_10.setText(
            _translate("GameGUI", "<html><head/><body><p><img src=\"../imgs/4.png\"/></p></body></html>"))
        self.solve_btn.setText(_translate("GameGUI", "Solve"))
        self.algorithm_box.setTitle(_translate("GameGUI", "Algorithm"))
        self.comboBox.setItemText(0, _translate("GameGUI", "Depth-first"))
        self.comboBox.setItemText(1, _translate("GameGUI", "Breadth-first"))
        self.comboBox.setItemText(2, _translate("GameGUI", "A* Euclidean"))
        self.comboBox.setItemText(3, _translate("GameGUI", "A* Manhattan"))
        self.configuration_box.setTitle(_translate("GameGUI", "Configuration"))
        self.custom_config.setHtml(_translate("GameGUI",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">12345678</span></p></body></html>"))
        self.set_btn.setText(_translate("GameGUI", "Set"))
        self.shuffle_btn.setText(_translate("GameGUI", "Shuffle"))
        self.options_box.setTitle(_translate("GameGUI", "Options"))
        self.option_ch_1.setText(_translate("GameGUI", "CheckBox"))
        self.option_ch_2.setText(_translate("GameGUI", "CheckBox"))
        self.option_ch_3.setText(_translate("GameGUI", "CheckBox"))
        self.statusbar.setStatusTip(_translate("GameGUI", "I\'m exponentially fine..."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    GameGUI = QtWidgets.QMainWindow()
    ui = Ui_GameGUI()
    ui.setupUi(GameGUI)
    GameGUI.show()
    sys.exit(app.exec_())
